Select * from AspNetRoles
Select * from AspNetUserClaims
Select * from AspNetUserLogins
Select * from AspNetUserRoles
Select * from AspNetUsers
Select * from ExpenseCategory
Select * from GMembers
Select * from MemberType
Select * from PayTaleGroup
Select * from PayTaleGTran
Select * from PayTales
Select * from PayTaleUser
Select * from Wallet
