//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTale.API.DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTran
    {
        public long Id { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string GTranCode { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
