//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTale.API.DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberType
    {
        public long MTypeId { get; set; }
        public string MType { get; set; }
    }
}
