//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTale.API.DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTale
    {
        public long Id { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string GTranCode { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<long> MTypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Category { get; set; }
        public string Note { get; set; }
        public string BillSnap { get; set; }
        public Nullable<System.DateTime> PayTaleDate { get; set; }
        public string PayMaster { get; set; }
    }
}
