//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTale.API.DAL.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public long Id { get; set; }
        public Nullable<long> GroupId { get; set; }
        public string GTranCode { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<decimal> WalletAmount { get; set; }
        public string AmtType { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string PayMaster { get; set; }
    }
}
